### ISSUE TITLE
NameError: name 'xrange' is not defined

### ISSUE THREAD

**Issue by atrdev-rgb** [pdf-utilities/inject_javascript#4]
OS Windows 
![image](https://user-images.githubusercontent.com/34670899/83345299-2a289000-a31a-11ea-93f5-9453311b3231.png)

**Comment by S0AndS0** [comment]
Thank you for reporting this issue.


I can confirm that this is a bug for Python version 3 or greater, and this bug stems from originally writing the project in Python version 2 where `xrange` did exist.


Version `v0.0.7` of this project should fix this issue by changing `xrange` to `range`, and upgrading via Pip will likely resolve current range realted errors...


```bash
pip3 install --user --upgrade inject-javascript
```


Please re-open this issue if range related errors persist.
